<h1>Decision Trees (Part 1)</h1>
<p>Given a data set we can use machine learning to create decision trees to make a complex decision based on data.  In this assignment we learn decision trees to classify  </p>
<p>We are given the following dataset to work with.</p>
<table>
    <tr><th>No.</th><th>Outlook</th><th>Temperature</th><th>Humidity</th><th>Windy</th><th>Class</th></tr>
    <tr><td>1</td><td>sunny</td><td>hot</td><td>high</td><td>false</td><td>N</td></tr>
    <tr><td>2</td><td>sunny</td><td>hot</td> <td>high</td> <td>true</td> <td>N</td></tr>
    <tr><td>3</td><td>overcast</td><td>hot</td> <td>high</td> <td>false</td> <td>P</td></tr>
    <tr><td>4</td><td>rain</td><td>mild</td> <td>high</td> <td>false</td> <td>P</td></tr>
    <tr><td>5</td><td>rain</td><td>cool</td> <td>normal</td> <td>false</td> <td>P</td></tr>
    <tr><td>6</td><td>rain</td><td>cool</td> <td>normal</td> <td>true</td> <td>N</td></tr>
    <tr><td>7</td><td>overcast</td><td>cool</td> <td>normal</td> <td>true</td> <td>P</td></tr>
    <tr><td>8</td><td>sunny</td><td>mild</td> <td>high</td> <td>false</td> <td>N</td></tr>
    <tr><td>9</td><td>sunny</td><td>cool</td> <td>normal</td> <td>false</td> <td>P</td></tr>
    <tr><td>10</td><td>rain</td><td>mild</td> <td>normal</td> <td>false</td> <td>P</td></tr>
    <tr><td>11</td><td>sunny</td><td>mild</td> <td>normal</td> <td>true</td> <td>P</td></tr>
    <tr><td>12</td><td>overcast</td><td>mild</td> <td>high</td> <td>true</td> <td>P</td></tr>
    <tr><td>13</td><td>overcast</td><td>hot</td> <td>normal</td> <td>false</td> <td>P</td></tr>
    <tr><td>14</td><td>rain</td><td>mild</td> <td>high</td> <td>true</td> <td>N</td></tr>
</table>

<p>Notice we have a number of enumerated features.  For instance the <b>outlook</b> category can be either sunny, overcast or rain.  The <b>temperature</b> can be hot, mild or cool, the <b>humidty</b> can be high or normal.  To make it easier to handle this programatically we can transform these features into <b>1-hot vectors</b>; or in the case of the humidty just a simple boolean.  So instead of our original feature set lets use the following list of binary variables: Sunny, Overcast, Rainy, Hot Mild, Cool, Humid, Windy.  With this in mind we can use the table shown below as the input to our algorithms.</p>

<table>
    <tr><th>No.</th><th>Sunny</th><th>Overcast</th><th>Rainy</th><th>Hot</th><th>Mild</th><th>Cool</th><th>Humid</th><th>Windy</th><th>Class</th></tr>
    <tr><td>1</td> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>N</th></tr>
    <tr><td>2</td> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>T</th> <th>N</th></tr>
    <tr><td>3</td> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>P</th></tr>
    <tr><td>4</td> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>P</th></tr>
    <tr><td>5</td> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>P</th></tr>
    <tr><td>6</td> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>N</th></tr>
    <tr><td>7</td> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>P</th></tr>
    <tr><td>8</td> <th>T</th> <th>F</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>N</th></tr> 
    <tr><td>9</td> <th>T</th> <th>F</th> <th>F</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>P</th></tr>
    <tr><td>10</td> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>F</th> <th>P</th></tr>
    <tr><td>11</td> <th>T</th> <th>F</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>P</th></tr>
    <tr><td>12</td> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>T</th> <th>P</th></tr>
    <tr><td>13</td> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>F</th> <th>F</th> <th>F</th> <th>P</th></tr>
    <tr><td>14</td> <th>F</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>F</th> <th>T</th> <th>T</th> <th>N</th></tr>
</table>

<h3 id="randomdecisiontree">Decision Trees - Random Feature Selection</h3>
<p>When learning a decision tree we can use the following algorithm...</p><br>
<code>While there are data points left to classify:
    1. Pick a feature or features to branch on.
    2. Divide the input data based on the decision.
    3. If either set of the divided data has a single class then let that be the leaf of the tree.</code>

In [1]:
import numpy as np
import decision_tree as dt

converter = {'sunny':0, 'overcast':1, 'rain':2, 'hot':0, 'mild':1,'cool':2, 'high':0, 'normal':1, 'true':1, 'false':0, 'N':0, 'P':1}

data = [['sunny', 'hot', 'high', 'false', 'N'],
        ['sunny', 'hot', 'high', 'true', 'N'],
        ['overcast', 'hot', 'high', 'false', 'P'],
        ['rain', 'mild', 'high', 'false', 'P'],
        ['rain', 'cool', 'normal', 'false', 'P'],
        ['rain', 'cool', 'normal', 'true', 'N'],
        ['overcast', 'cool', 'normal', 'true', 'P'],
        ['sunny', 'mild', 'high', 'false', 'N'],
        ['sunny', 'cool', 'normal', 'false', 'P'],
        ['rain', 'mild', 'normal', 'false', 'P'],
        ['sunny', 'mild', 'normal', 'true', 'P'],
        ['overcast', 'mild', 'high', 'true', 'P'],
        ['overcast', 'hot', 'normal', 'false', 'P'],
        ['rain', 'mild', 'high', 'true', 'N']]

np_data = np.zeros((len(data), len(data[0])))

# convert the data into numbers...
for i, row in enumerate(data):
    for k, col in enumerate(row):
        np_data[i,k] = converter[col]
        
X = np_data[:,:-1]
Y = np_data[:,-1]
print(X)
print(Y)

tree = dt.createTree(X,Y,[i for i in range(X.shape[1])], dt.inOrderSelector)

parts = dt.partition(X,Y,0)
for p in parts:
    print(p[0])
    print(p[1])


[[0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [2. 2. 1. 0.]
 [2. 2. 1. 1.]
 [1. 2. 1. 1.]
 [0. 1. 0. 0.]
 [0. 2. 1. 0.]
 [2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 0.]
 [2. 1. 0. 1.]]
[0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0.]


TypeError: createTree() missing 1 required positional argument: 'get_idx_fx'

In [12]:
from sklearn import tree
from sklearn.externals.six import StringIO
import pydotplus
from IPython.display import Image

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)
dot_data = StringIO()
tree.export_graphviz(clf, out_file=dot_data, filled=True, rounded=True, special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

InvocationException: GraphViz's executables not found